server:
    port: 8080
spring:
    application:
        name: commerce
    datasource:
        url: jdbc:log4jdbc:postgresql://localhost:5432/postgres
        username: postgres
        password: postgres
        driver-class-name: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
    mybatis:
        config-location: classpath:mybatis-config.xml